# Generated by Django 5.1.2 on 2024-12-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0004_relatedmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
